var annotated =
[
    [ "pmp", "namespacepmp.html", [
      [ "VertexCurvature", "structpmp_1_1_vertex_curvature.html", null ],
      [ "Heap", "classpmp_1_1_heap.html", "classpmp_1_1_heap" ],
      [ "NormalCone", "classpmp_1_1_normal_cone.html", "classpmp_1_1_normal_cone" ],
      [ "Quadric", "classpmp_1_1_quadric.html", "classpmp_1_1_quadric" ],
      [ "SurfaceCurvature", "classpmp_1_1_surface_curvature.html", "classpmp_1_1_surface_curvature" ],
      [ "SurfaceFactory", "classpmp_1_1_surface_factory.html", null ],
      [ "SurfaceFairing", "classpmp_1_1_surface_fairing.html", "classpmp_1_1_surface_fairing" ],
      [ "SurfaceFeatures", "classpmp_1_1_surface_features.html", "classpmp_1_1_surface_features" ],
      [ "SurfaceGeodesic", "classpmp_1_1_surface_geodesic.html", "classpmp_1_1_surface_geodesic" ],
      [ "SurfaceHoleFilling", "classpmp_1_1_surface_hole_filling.html", "classpmp_1_1_surface_hole_filling" ],
      [ "SurfaceNormals", "classpmp_1_1_surface_normals.html", null ],
      [ "SurfaceParameterization", "classpmp_1_1_surface_parameterization.html", "classpmp_1_1_surface_parameterization" ],
      [ "SurfaceRemeshing", "classpmp_1_1_surface_remeshing.html", "classpmp_1_1_surface_remeshing" ],
      [ "SurfaceSimplification", "classpmp_1_1_surface_simplification.html", "classpmp_1_1_surface_simplification" ],
      [ "SurfaceSmoothing", "classpmp_1_1_surface_smoothing.html", "classpmp_1_1_surface_smoothing" ],
      [ "SurfaceSubdivision", "classpmp_1_1_surface_subdivision.html", "classpmp_1_1_surface_subdivision" ],
      [ "SurfaceTriangulation", "classpmp_1_1_surface_triangulation.html", "classpmp_1_1_surface_triangulation" ],
      [ "TriangleKdTree", "classpmp_1_1_triangle_kd_tree.html", "classpmp_1_1_triangle_kd_tree" ],
      [ "BoundingBox", "classpmp_1_1_bounding_box.html", "classpmp_1_1_bounding_box" ],
      [ "Matrix", "classpmp_1_1_matrix.html", "classpmp_1_1_matrix" ],
      [ "MemoryUsage", "classpmp_1_1_memory_usage.html", null ],
      [ "Handle", "classpmp_1_1_handle.html", "classpmp_1_1_handle" ],
      [ "Vertex", "classpmp_1_1_vertex.html", null ],
      [ "Halfedge", "classpmp_1_1_halfedge.html", null ],
      [ "Edge", "classpmp_1_1_edge.html", null ],
      [ "Face", "classpmp_1_1_face.html", null ],
      [ "VertexProperty", "classpmp_1_1_vertex_property.html", "classpmp_1_1_vertex_property" ],
      [ "HalfedgeProperty", "classpmp_1_1_halfedge_property.html", "classpmp_1_1_halfedge_property" ],
      [ "EdgeProperty", "classpmp_1_1_edge_property.html", "classpmp_1_1_edge_property" ],
      [ "FaceProperty", "classpmp_1_1_face_property.html", "classpmp_1_1_face_property" ],
      [ "ObjectProperty", "classpmp_1_1_object_property.html", "classpmp_1_1_object_property" ],
      [ "SurfaceMesh", "classpmp_1_1_surface_mesh.html", "classpmp_1_1_surface_mesh" ],
      [ "Timer", "classpmp_1_1_timer.html", "classpmp_1_1_timer" ],
      [ "IOFlags", "structpmp_1_1_i_o_flags.html", "structpmp_1_1_i_o_flags" ],
      [ "InvalidInputException", "classpmp_1_1_invalid_input_exception.html", null ],
      [ "SolverException", "classpmp_1_1_solver_exception.html", null ],
      [ "AllocationException", "classpmp_1_1_allocation_exception.html", null ],
      [ "TopologyException", "classpmp_1_1_topology_exception.html", null ],
      [ "IOException", "classpmp_1_1_i_o_exception.html", null ],
      [ "Version", "classpmp_1_1_version.html", null ],
      [ "MeshViewer", "classpmp_1_1_mesh_viewer.html", "classpmp_1_1_mesh_viewer" ],
      [ "Shader", "classpmp_1_1_shader.html", "classpmp_1_1_shader" ],
      [ "SurfaceMeshGL", "classpmp_1_1_surface_mesh_g_l.html", "classpmp_1_1_surface_mesh_g_l" ],
      [ "TrackballViewer", "classpmp_1_1_trackball_viewer.html", "classpmp_1_1_trackball_viewer" ],
      [ "Window", "classpmp_1_1_window.html", "classpmp_1_1_window" ]
    ] ]
];