# pypmp/__init__.pyi
from __future__ import annotations
from typing import Any, Iterator, overload, Union, Tuple

Scalar = float

# -----------------------------
# Matrix types
# -----------------------------

class Point:
    """3D vector"""

    def __init__(self, x: Scalar = 0.0, y: Scalar = 0.0, z: Scalar = 0.0) -> None: ...
    def __getitem__(self, key: Union[int, Tuple[int, int]]) -> Scalar: ...
    def __setitem__(self, key: Union[int, Tuple[int, int]], value: Scalar) -> None: ...
    def __len__(self) -> int: ...
    def normalize(self) -> None: ...
    def __add__(self, other: Point) -> Point: ...
    def __sub__(self, other: Point) -> Point: ...
    def __mul__(self, scalar: Scalar) -> Point: ...
    def __truediv__(self, scalar: Scalar) -> Point: ...
    def __repr__(self) -> str: ...

class Mat3:
    """3x3 matrix"""

    def __init__(self, p0: Point, p1: Point, p2: Point) -> None: ...
    def __getitem__(self, key: Union[int, Tuple[int, int]]) -> Scalar: ...
    def __setitem__(self, key: Union[int, Tuple[int, int]], value: Scalar) -> None: ...
    def __len__(self) -> int: ...
    def normalize(self) -> None: ...
    def __add__(self, other: Mat3) -> Mat3: ...
    def __sub__(self, other: Mat3) -> Mat3: ...
    def __mul__(self, scalar: Scalar) -> Mat3: ...
    def __truediv__(self, scalar: Scalar) -> Mat3: ...
    def __repr__(self) -> str: ...

# -----------------------------
# SurfaceMesh + Handles
# -----------------------------

class Handle:
    """Base handle type used by mesh elements."""
    def __init__(self) -> None: ...
    def idx(self) -> int: ...

class Vertex(Handle):
    """Vertex handle"""
    def __init__(self) -> None: ...

class Face(Handle):
    """Face handle"""
    def __init__(self) -> None: ...

class Edge(Handle):
    """Edge handle"""
    def __init__(self) -> None: ...

class Halfedge(Handle):
    """Halfedge handle"""
    def __init__(self) -> None: ...

class SurfaceMesh:
    """Polygonal surface mesh"""

    def __init__(self) -> None: ...
    def add_vertex(self, point: Point) -> Vertex: ...
    def add_triangle(self, v0: Vertex, v1: Vertex, v2: Vertex) -> Face: ...
    def n_vertices(self) -> int: ...
    def n_edges(self) -> int: ...
    def n_faces(self) -> int: ...

__all__ = [
    "Scalar",
    "Point",
    "Mat3",
    "Handle",
    "Vertex",
    "Face",
    "Edge",
    "Halfedge",
    "SurfaceMesh",
]
